module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'orders',
    WISHLIST_COLLECTION:'wishlist',
    ADMIN_COLLECTION:'admin',
    DISPLAY_COLLECTION:'display',
    DELIVERY_COLLECTION:'delivery',
    SUPERADMIN_COLLECTION:'superadmin',
    CONTACT_COLLECTION:'contact',
    COUPONS_COLLECTION:'coupons',
    RATING_COLLECTION:'reviews'
}